import { Component, OnInit } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { Capacitor } from '@capacitor/core';
import { StatusBar, Style } from '@capacitor/status-bar';
import { addIcons } from 'ionicons';
import {
  add,
  alertCircleOutline,
  arrowBack,
  arrowForward,
  bagHandleOutline,
  bodyOutline,
  bookmarksOutline,
  calendarOutline,
  callOutline,
  card,
  cardOutline,
  cartOutline,
  cashOutline,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  closeCircleOutline,
  colorPaletteOutline,
  chevronBack,
  chevronDown,
  chevronForward,
  chevronUp,
  close,
  closeCircle,
  cloudOfflineOutline,
  cloudUploadOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  downloadOutline,
  eyeOffOutline,
  eyeOutline,
  folderOpenOutline,
  funnelOutline,
  globeOutline,
  gridOutline,
  heart,
  heartOutline,
  homeSharp,
  imageOutline,
  informationCircleOutline,
  locationOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  peopleOutline,
  personCircleOutline,
  personOutline,
  pricetagOutline,
  refreshOutline,
  remove,
  resizeOutline,
  searchOutline,
  serverOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  sparkles,
  sparklesOutline,
  starOutline,
  statsChartOutline,
  trashOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  imports: [IonApp, IonRouterOutlet],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit {
  async ngOnInit() {
    if (Capacitor.isNativePlatform()) {
      try {
        await StatusBar.setOverlaysWebView({ overlay: false });
        await StatusBar.setBackgroundColor({ color: '#fefefa' });
        await StatusBar.setStyle({ style: Style.Light });
      } catch {}
    }
  }

  constructor() {
    addIcons({
      add,
      alertCircleOutline,
      arrowBack,
      arrowForward,
      bagHandleOutline,
      bodyOutline,
      bookmarksOutline,
      calendarOutline,
      callOutline,
      card,
      cardOutline,
      cartOutline,
      cashOutline,
      checkmark,
      checkmarkCircle,
      checkmarkCircleOutline,
      closeCircleOutline,
      colorPaletteOutline,
      chevronBack,
      chevronDown,
      chevronForward,
      chevronUp,
      close,
      closeCircle,
      cloudOfflineOutline,
      cloudUploadOutline,
      createOutline,
      cubeOutline,
      documentTextOutline,
      downloadOutline,
      eyeOffOutline,
      eyeOutline,
      folderOpenOutline,
      funnelOutline,
      globeOutline,
      gridOutline,
      heart,
      heartOutline,
      homeSharp,
      imageOutline,
      informationCircleOutline,
      locationOutline,
      lockClosedOutline,
      logOutOutline,
      mailOutline,
      peopleOutline,
      personCircleOutline,
      personOutline,
      pricetagOutline,
      refreshOutline,
      remove,
      resizeOutline,
      searchOutline,
      serverOutline,
      settingsOutline,
      shieldCheckmarkOutline,
      sparkles,
      sparklesOutline,
      starOutline,
      statsChartOutline,
      trashOutline,
    });
  }
}